---
apiVersion: v1
kind: Namespace

metadata:
    name: nwapp
    labels:
        version: v1
---
apiVersion: v1
kind: Secret
metadata:
    name: nw-secret
    namespace: nwapp

data:
    db_password: aGVsbG8=

---
apiVersion: v1
kind: ConfigMap
metadata:
    name: nw-config
    namespace: nwapp

data:
    db_user: root
    db_host: nwdb-svc.nwapp.svc.cluster.local
