---
apiVersion: v1
kind: Namespace

metadata:
    name: nwdb
    labels:
        version: v1

---
apiVersion: v1
kind: Secret
metadata:
    name: nw-secret
    namespace: nwdb

data:
    db_password: aGVsbG8=

---
apiVersion: v1
kind: ConfigMap
metadata:
    name: nw-config
    namespace: nwdb
data:
    db_password: changeit

---
apiVersion: apps/v1
kind: Deployment

metadata:
    name: nwdb-deploy
    namespace: nwdb
    labels:
        name: nw

spec:
    replicas: 1
    selector:
        matchLabels:
           name: nw
    minReadySeconds: 30
    template:
        metadata:
            name: nwdb-pod
            labels:
                name: nw
        spec:
            containers:
            - name: nwdb
              image: ydock2/nwdb1:v1
              imagePullPolicy: IfNotPresent
              env:
              - name: MYSQL_ROOT_PASSWORD
                valueFrom: 
                    secretKeyRef:
                        name: nw-secret
                        key: db_password
              ports:
              - containerPort: 3306

---


