---
apiVersion: apps/v1
kind: Deployment

metadata:
    name: nwapp-deploy
    namespace: nwapp
    labels:
        name: nw

spec:
    replicas: 2
    selector:
        matchLabels:
           name: nw
    minReadySeconds: 30
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 1
    template:
        metadata:
            name: nwapp-pod
            labels:
                name: nw
                version: v1
        spec:
            containers:
            - name: nwapp
              image: stackupiss/northwind-app:v2
              imagePullPolicy: IfNotPresent
              livenessProbe:
                  httpGet:
                      path: /health
                      port: nw-port
                  timeout 
              env:
              - name: DB_PASSWORD
                valueFrom: 
                    secretKeyRef:
                        name: nw-secret
                        key: db_password
              - name: DB_HOST
                valueFrom:
                    configMapKeyRef:
                        name: nw-config
                        key: db_host 
              - name: DB_USER
                valueFrom:
                    configMapKeyRef:
                        name: nw-config
                        key: db_user 
              - name: INSTANCE_IP_ADDRESS
                valueFrom:
                    fieldRef:
                        fieldPath: status.hostIP
              ports:
              - name: nw-port
                containerPort: 3000

---



