apiVersion: apps/v1
kind: Deployment
metadata:
  name: appv2-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      name: myapp
  template:
    metadata:
      labels:
        name: myapp
        version: v2
    spec:
      containers:
      - name: myappv2-container
        image: stackupiss/northwind-app:v2

        resources:
          limits:
            memory: "55M"
            cpu: "20m"
        env:
          - name: DB_HOST
            value: mydb-svc.default.svc.cluster.local
          - name: DB_PORT
            value: "3306"
          - name: DB_USER
            value: root
          - name: DB_PASSWORD
            value: changeit
        ports:
        - containerPort: 3000
          name: myapp-port
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
