---
apiVersion: apps/v1
kind: Deployment

metadata:
    name: nwdb-deploy
    namespace: nwapp
    labels:
        name: nw

spec:
    replicas: 1
    selector:
        matchLabels:
            name: nw
    template:
        metadata:
            name: nwdb-pod
            labels:
                name: nw
        spec:
            containers:
            - name: nwdb-container
              image: ydock2/nwdb1:v1
              imagePullPolicy: IfNotPresent
              env:
              - name: MYSQL_ROOT_PASSWORD
                valueFrom: 
                    secretKeyRef:
                        name: nw-secret
                        key: db_password
              ports:
              - name: nw-port
                containerPort: 3306

---
apiVersion: v1
kind: Service

metadata:
    name: nwdb-svc
    namespace: nwapp
    labels:
        name: nwdb-svc
        version: v1

spec:
    type: ClusterIP
    selector: 
        name: nw
    ports:
    - name: nwdb-port
      port: 3306
      targetPort: nw-port
