{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "mlapp.serviceAccountName" . }}
  labels:
{{ include "mlapp.labels" . | indent 4 }}
{{- end -}}
