---
apiVersion: v1
kind: Namespace

metadata:
    name: myns
    labels:
        version: v1
---
apiVersion: apps/v1
kind: Deployment

metadata:
    name: fortune-deploy
    namespace: myns
    labels:
        name: fortune
        version: v1

spec:
    replicas: 3
    selector:
        matchLabels:
            name: fortune
            version: v1
    template:
        metadata:
            name: fortune-pod
            labels:
                name: fortune
                version: v1
        spec:
            containers:
            - name: fortune-container
              image: ydock2/myfortuneapp:v2
              imagePullPolicy: IfNotPresent
              env:
              - name: APP_PORT
                value: "3000"
              ports:
              - name: http
                containerPort: 3000
