version: '3'

networks:
    appnet:

volumes:
    appvol:

services:
    nwdb:
        image: ydock2/nwdb1:v1
        build:
            context: ./database
        environment:
        - MYSQL_ROOT_PASSWORD=changeit
        networks:
        - appnet
        volumes:
        - appvol: /var/lib/mysql
    nwapp:
        image: ydock2/nwapp:v1
        build:
            context: ./server
        environment:
        - DB_HOST=nwdb
        ports:
        - 80:3000
        networks:
        - appnet

